name: release-insight

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      # ----------------------------------------------------------
      # Setup
      # ----------------------------------------------------------

      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.100"

      # ----------------------------------------------------------
      # Test and Build
      # ----------------------------------------------------------

      - name: Server TestSuite
        run: |
          tzutil /s "Pacific Standard Time"
          dotnet test server/test

      - run: yarn --cwd client/insight install --frozen-lockfile
      - run: yarn --cwd client/insight test
      - run: yarn --cwd client/insight run build

      - name: Build Mazak
        shell: pwsh
        run: ./build/insight-installer-build.ps1 mazak $ENV:GITHUB_REF.Substring(11)

      - name: Build Makino
        shell: pwsh
        run: ./build/insight-installer-build.ps1 makino $ENV:GITHUB_REF.Substring(11)

      - name: Install Backup Viewer Deps
        run: yarn --cwd client/backup-viewer install --frozen-lockfile

      - name: Update Backup Viewer Version
        shell: pwsh
        run: yarn --cwd client/backup-viewer version --no-git-tag-version --new-version $ENV:GITHUB_REF.Substring(11)

      # ----------------------------------------------------------
      # Release
      # ----------------------------------------------------------

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: FMS Insight ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Mazak
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: installers/FMS Insight Mazak Install.msi
          asset_name: FMS Insight Mazak Install.msi
          asset_content_type: application/octet-stream

      - name: Upload Makino
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: installers/FMS Insight Makino Install.msi
          asset_name: FMS Insight Makino Install.msi
          asset_content_type: application/octet-stream

      # https://github.com/electron-userland/electron-builder/issues/4176
      - name: Temporarily fix electron-builder
        run: sed -i 's/\^\[\\w/\^\[.\\w/g' client/backup-viewer/node_modules/builder-util/out/util.js
        shell: bash

      - name: Build and Upload Backup Viewer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn --cwd client/backup-viewer run dist --publish=always

      - name: Build reverse proxy
        shell: pwsh
        run: ./server/reverse-proxy/build.ps1 -Version $ENV:GITHUB_REF.Substring(11)

      - name: Upload reverse proxy
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: server/reverse-proxy/reverse-proxy.zip
          asset_name: FMS Insight Reverse Proxy.zip
          asset_content_type: application/octet-stream
